apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-secret-generator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mittwald/kubernetes-secret-generator.git
    path: deploy/cert-manager-dns-lexicon-webhook
    targetRevision: master
    helm:
      releaseName: kubernetes-secret-generator
      values:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubernetes-secret-generator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
