apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: timemachine

resources:
  - timemachine-ns.yaml
  - timemachine-pvc.yaml
  - timemachine-svc.yaml
  - samba-deploy.yaml
  #- timemachine-deploy.yaml
