apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: timemachine

resources:
  - timemachine-svc.yaml
  - https://raw.githubusercontent.com/mbentley/docker-timemachine/master/timemachine-k3s.yaml

patches:
  - target:
      kind: StatefulSet
      name: timemachine
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: timemachine
      spec:
        serviceName: timemachine
        template:
          spec:
            containers:
              - name: timemachine
                env:
                  - name: ADVERTISED_HOSTNAME
                    value: "timemachine.manhatten.uxn.nl"
                  - name: PASSWORD
                    value:
                    valueFrom:
                      secretKeyRef:
                        name: password
                        key: password

  - target:
      version: v1
      kind: StatefulSet
      name: timemachine
    patch: |-
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        name: timemachine
        namespace: timemachine
      spec:
        volumeClaimTemplates:
          - metadata:
              name: tm
            spec:
              accessModes:
                - ReadWriteOnce
              storageClassName: zfs-localpv-default
              resources:
                requests:
                  storage: 500Gi

  - target:
      version: v1
      kind: Namespace
      name: timemachine
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: timemachine
        labels:
          pod-security.kubernetes.io/audit: privileged
          pod-security.kubernetes.io/enforce: privileged
          pod-security.kubernetes.io/warn: privileged

  - target:
      kind: StatefulSet
      name: timemachine
    patch: |-
      apiVersion: v1
      kind: StatefulSet
      metadata:
        name: timemachine
      spec:
        serviceName: timemachine

  - target:
      kind: Service
      name: timemachine-tcp
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: timemachine-tcp
       $patch: delete
  #
  # - target:
  #     kind: Service
  #     name: timemachine-udp
  #   patch: |-
  #     apiVersion: v1
  #     kind: Service
  #     metadata:
  #       name: timemachine-udp
  #      $patch: delete

  # - target:
  #     kind: Service
  #     name: timemachine-tcp
  #   patch: |-
  #     apiVersion: v1
  #     kind: Service
  #     metadata:
  #       name: timemachine-tcp
  #       namespace: timemachine
  #     spec:
  #       loadBalancerIP: 192.168.69.102
  #       type: LoadBalancer
  #
  # - target:
  #     kind: Service
  #     name: timemachine-udp
  #   patch: |-
  #     apiVersion: v1
  #     kind: Service
  #     metadata:
  #       name: timemachine-udp
  #       namespace: timemachine
  #     spec:
  #       loadBalancerIP: 192.168.69.102
  #       type: LoadBalancer
