apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
        - name: timemachine
          image: dperson/samba
          ports:
            - containerPort: 445 # Standard Samba port
          args:
            - "-p"
            - "-u"
            - "test;test"
            - "-s"
            - "timemachine;/timemachine;yes;no;no;test"
          volumeMounts:
            - name: samba-storage
              mountPath: /timemachine
      volumes:
        - name: samba-storage
          persistentVolumeClaim:
            claimName: timemachine
