apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timemachine
  namespace: timemachine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Gi
  storageClassName: zfs-localpv-default
