apiVersion: v1
kind: Service
metadata:
  name: timemachine
  namespace: timemachine
  labels:
    app: timemachine
spec:
  ports:
    - port: 139
      name: tcp139
    - port: 445
      name: tcp445
    - port: 137
      name: udp137
      protocol: UDP
    - port: 138
      name: udp138
      protocol: UDP
  type: LoadBalancer
  loadBalancerIP: 192.168.69.102
  selector:
    app: timemachine-udp
