apiVersion: v1
kind: Service
metadata:
  name: timemachine
spec:
  selector:
    app: samba
  ports:
    - protocol: TCP
      port: 445
      targetPort: 445
  type: LoadBalancer
  loadBalancerIP: 192.168.69.102
