apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://openebs.github.io/openebs
    chart: openebs
    targetRevision: 4.2.0
    helm:
      releaseName: openebs
      parameters:
        - name: zfs-localpv.zfsNode.encrKeysDir
          value: /var/openebs/keys
      values: |
        openebs-crds:
          csi:
            volumeSnapshots:
              enabled: true
              keep: true

        # Refer to https://github.com/openebs/dynamic-localpv-provisioner/blob/v4.2.0/deploy/helm/charts/values.yaml for complete set of values.
        localpv-provisioner:
          rbac:
            create: true

        # Refer to https://github.com/openebs/zfs-localpv/blob/v2.7.1/deploy/helm/charts/values.yaml for complete set of values.
        zfs-localpv:
          crds:
            zfsLocalPv:
              enabled: true
          csi:
            volumeSnapshots:
              enabled: true

        # Refer to https://github.com/openebs/lvm-localpv/blob/lvm-localpv-1.6.2/deploy/helm/charts/values.yaml for complete set of values.
        lvm-localpv:
          crds:
            lvmLocalPv:
              enabled: true
            csi:
              volumeSnapshots:
                enabled: false

        # Refer to https://github.com/openebs/mayastor-extensions/blob/v2.8.0/chart/values.yaml for complete set of values.
        mayastor:
          csi:
            node:
              initContainers:
                enabled: false
          etcd:
            # -- Kubernetes Cluster Domain
            clusterDomain: cluster.local
          localpv-provisioner:
            enabled: false
          crds:
            enabled: false

        # -- Configuration options for pre-upgrade helm hook job.
        preUpgradeHook:
          image:
            # -- The container image registry URL for the hook job
            registry: docker.io
            # -- The container repository for the hook job
            repo: bitnami/kubectl
            # -- The container image tag for the hook job
            tag: "1.25.15"
            # -- The imagePullPolicy for the container
            pullPolicy: IfNotPresent

        engines:
          local:
            lvm:
              enabled: false
            zfs:
              enabled: true
          replicated:
            mayastor:
              enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
