apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config
  namespace: htpc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: zfs-localpv-default
