apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbitt-download
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/shared-data
  storageClassName: hostpath
  persistentVolumeReclaimPolicy: Delete
