---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    storage: bookstack-db-storage
  name: bookstack-db-storage
  namespace: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    storage: bookstack-storage
  name: bookstack-storage
  namespace: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
