apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:stable
          env:
            - name: TZ
              value: "Europe/Amsterdam"
          volumeMounts:
            - name: config-volume
              mountPath: /config/config.yaml
              readOnly: true
            - name: home-assistant-config
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: home-assistant-config
            items:
              - key: configuration.yaml
                path: configuration.yaml
        - name: home-assistant-config
          persistentVolumeClaim:
            claimName: home-assistant-config
