apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-home-assistant-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
